apiVersion: v1
kind: Pod
metadata:
  name: whoami-pod-lp
  labels:
    app: whoami
spec:
  containers:
  - name: whoami-container
    image: subicura/whoami:1
    livenessProbe:
      httpGet:
        path: /not/exist
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 2
      periodSeconds: 5
      failureThreshold: 1