apiVersion: v1
kind: Pod
metadata:
  name: whoami-pod-health
  labels:
    app: whoami
spec:
  containers:
  - name: whoami-container
    image: subicura/whoami:1
    livenessProbe:
      httpGet:
        path: /
        port: 4567
    readinessProbe:
      httpGet:
        path: /
        port: 4567