apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: mongo-pv
spec:
  storageClassName: "" 
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mongodb
    fsType: ext4