apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deploy
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: echo
  template:
    metadata: 
      name: echo
      labels:
        app: echo
    spec:
      containers:
      - name: echo-container
        image: ghcr.io/subicura/echo:v1