apiVersion: v1
kind: Pod
metadata:
  name: echo-health
  labels:
    app: echo
spec:
  containers:
  - name: echo-conatiner
    image: ghcr.io/subicura/echo:v1
    livenessProbe:
      httpGet:
        path: /
        port: 3000
    readinessProbe:
      httpGet:
        path: /
        port: 3000