apiVersion: v1
kind: Pod
metadata:
  name: echo-pod-lp
  labels:
    app: echo
spec:
  containers:
  - name: echo-container
    image: ghcr.io/subicura/echo:v1
    livenessProbe:
      httpGet:
        path: /not/exist  # 존재하지 않는 path
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 2 # default 1
      periodSeconds: 5  # default 10
      failureThreshold: 1 # default 3
