apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb-container
    image: mariadb:10.7
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password