apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-svc
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: mysql
  ports:
  - protocol: TCP
    port: 3306