apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-pod
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: wordpress
      tier: frontend
  template:
    metadata: 
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:5.9.1-php8.1-apache
        env:
          - name: WORDPRESS_DB_HOST
            value: wordpress-mysql
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_PASSWORD
            value: password
        ports:
          - containerPort: 80
            name: wordpress