apiVersion: v1
kind: Service
metadata:
  name: wordpress-pod
  labels:
    app: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
    tier: frontend
  ports:
  - protocol: TCP
    port: 80